### ISSUE TITLE
Mathematical error

### ISSUE THREAD

**Issue by ghost** [CloudburstMC/Cloudburst#100]
Return value of org.cloudburstmc.server.player.Player's distance method (line 724 stable, 725 bleeding) should be
(int) Math.sqrt(dx * dx + dz * dz);
Also why are you using integer as returning type of a entity distance method use float at least

**Comment by DaMatrix** [comment]
That method is actually never used, it's probably left over from the legacy Nukkit code.

Also it probably isn't wrong. Using the squared distance is quite common when you only need to compare which distance is longer and don't need to know how long it actually is. `sqrt()` is expensive. Although you are correct, the method should be returning `double`, and probably renamed to `distanceSq`.

**Comment by ghost** [comment]
Random fact: Java's Math.sqrt() and math.h's sqrt() (glibc) both use IEEE 754 sqrt (glibc first tries kernel's method) method so Java has almost the same speed of C (glibc) in terms of calculating square root. [[1]](https://github.com/openjdk/jdk/blob/master/src/java.base/share/native/libfdlibm/e_sqrt.c) [[2]](https://sourceware.org/git/?p=glibc.git;a=blob;f=math/w_sqrt_compat.c;h=cab369d2e114bff0c08f69c9e9916ce876002286;hb=HEAD)

Also Java uses native code through JNI for its default math implementation (StrictMath.c) so it should be same with glibc in terms of memory usage

**Comment by Creeperface01** [comment]
I think the point is that even the fastest sqrt implementation is still considerably slower than the other common operations

**Comment by ghost** [comment]
> I think the point is that even the fastest sqrt implementation is still considerably slower than the other common operations

"Random"
