### ISSUE TITLE
The dependy in "api-changes" branch's pom.xml have some problem

### ISSUE THREAD

**Issue by smartcmd** [CloudburstMC/Cloudburst#118]
I found a problem in branch "api-changes"
the dependy "cloudburst-api' is not suit in this branch and its file in maven repo is not right
it need API "api-changes" branch but not bleeding branch
I can't solve this problem because the dependy is in the repo,I can't change it.I think you should update the file.thx

**Comment by Sleepybear** [comment]
The api-changes branch has been merged into master and the API Module dependency is available in maven.
