### ISSUE TITLE
kor console encoding broken bug

### ISSUE THREAD

**Issue by jiwon02971** [CloudburstMC/Cloudburst#124]
### Expected Behavior

Korean encoding on console is broken

### Actual Behavior

Korean encoding is broken like this:
04:48:14 [INFO ] Minecraft: Bedrock Edition �꽌踰� 踰꾩쟾 1.16.20�쓣(瑜�) �떆�옉�븯�뒗 以묒엯�땲�떎

### Steps to Reproduce

first Run cb server with java -jar Cloudburst.jar
and enter ko_KR

### Debug information

* Debug link:
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:

- [] I included a `/debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of Nukkit
- [] I Made sure the bug/error is not caused by a plugin

**Comment by SupremeMortal** [comment]
Should be fixed in b1fb139e3cd1b8ff21dfc77ad9e13459bf1c4f10
Please let me know if this is still an issue.
