### ISSUE TITLE
Build Failure Installing

### ISSUE THREAD

**Issue by Hricxo** [CloudburstMC/Cloudburst#135]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cloudburst-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 177 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ cloudburst-server ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.959 s
[INFO] Finished at: 2021-11-13T22:44:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cloudburst-server: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile failed: Unsupported major.minor version 61.0 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

What am I missing here, followed installations steps so, whats up

**Comment by Sleepybear** [comment]
Are you using Java 16 or 17 to compile?

**Comment by IWareQ** [comment]
use java 17

**Comment by Sleepybear** [comment]
You'll want to double check, because that error is indicating you are trying to compile with Java 16 or below.

**Comment by SupremeMortal** [comment]
Maven will use whatever your `JAVA_HOME` environment variable is set to, so make sure it has been updated.
