### ISSUE TITLE
Crash on first boot.

### ISSUE THREAD

**Issue by popkechupki** [CloudburstMC/Cloudburst#146]
### Expected Behavior
Proceed to initial server start after selecting language "ja_JP".

### Actual Behavior
Cloudburst crashed immediately after "ja_JP" selected.

### Steps to Reproduce

Execute "java -jar Cloudburst.jar" then select "ja_JP" for default language on first boot.

### Debug information

I can't execute debugpaste command because of the timing the crash happens.

### Crashdump, Backtrace or Other Files

https://www.toptal.com/developers/hastebin/ewihehutap.properties
**Checklist**:

- [] I included a `/debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of Cloudburst
- [x] I Made sure the bug/error is not caused by a plugin

**Comment by SupremeMortal** [comment]
Duplicate of #145
