### ISSUE TITLE
Nukkit wont run

### ISSUE THREAD

**Issue by xandaaah** [CloudburstMC/Cloudburst#152]
### Expected Behavior
Nukkit to run

### Actual Behavior
Nukkit didnt run

### Steps to Reproduce
Run nukkit

### Debug information
None because nukkit wont run

### Crashdump, Backtrace or Other Files
https://gist.github.com/Xanderplayz16/46bf06bac11bfcbd50d0542250095776

**Checklist**:

- [] I included a `/debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of Nukkit
- [x] I Made sure the bug/error is not caused by a plugin

**Comment by Sleepybear** [comment]
This isn't nukkit. Cloudburst needs updated still, and if you want it to run right now you need to add an opens clause to your start command. 

If you're trying to run nukkit, see CloudburstMC\Nukkit

**Comment by xandaaah** [comment]
What is a "opens clause"?

**Comment by xandaaah** [comment]
I thought this reposotory was for nukkit and I never knew cloudburst was making cloudburst server!

**Comment by xandaaah** [comment]
Also should I use Nukkit or this?

**Comment by Creeperface01** [comment]
> Also should I use Nukkit or this?

Cloudburst server should now be used only for testing or development purposes so otherwise use nukkit instead
