### ISSUE TITLE
Player v.s. player - Reach

### ISSUE THREAD

**Issue by DayzePvP** [CloudburstMC/Cloudburst#49]
### Expected Behavior
Player can always hit each other as long as their in range of one another.
Ex: Player 1 is hitting player 2 while always in range, player 2 is fighting back while in range, there are no player distance calculations that have gone wrong.?

### Actual Behavior
From player 2's perspective, it looks like player 1 has a 6/7 block reach.
Ex: Player 1 has made player 2 "fly" by hitting them rapidly in the air. Now Player 1 has an advantage because its now more difficult for player 2 to hit back. On player 1's screen, it looks like player 2 is able to hit him. But on player 2's screen, it looks like player 1 is a good 6 or 7 blocks away so therefore player 2 is not able to hit player 1 very easily.

Thnx in advance

**Comment by Creeperface01** [comment]
It's caused by network latency just like in every other multiplayer game. There's not an easy way of checking that. However some anti cheats might have something to reduce the difference
