### ISSUE TITLE
When you have landed you will be teleported back

### ISSUE THREAD

**Issue by LucGamesYT** [CloudburstMC/Cloudburst#54]
### Actual Behavior
If you want to land from GameMode Creative you will be teleported back to the spawn point

And after a few blocks you cannot place any more blocks and are teleported back again 

### Steps to Reproduce
1. Join server
2. Fly a little bit 
3. Land on ground

Video:
https://youtu.be/D3Cb2Z4buFs

**Comment by Kazzuk** [comment]
I tested this a little bit and it’s just not creative itself, it’s creative and spectator, when you start flying and land on the ground or change back from being spectator you will teleported back to your last position before flying or going into spectator, so it’s not your spawn point or world spawn
