### ISSUE TITLE
World Generation +

### ISSUE THREAD

**Issue by DayzePvP** [CloudburstMC/Cloudburst#68]
### Expected Behavior
World would generate a different seed every time a new world is loaded in. 
World would change to your imported world if loaded in.

### Actual Behavior
World is always the same every time even if loaded in a new version.
World is always the same even imported worlds would set to default.

### Steps to Reproduce
Stop server
Import your custom bedrock world and load it in
Join in
Realize its the default world

**Comment by Sleepybear** [comment]
You would need to either overwrite the default world with your world, or change the default world name in the cloudburst.yml file.

**Comment by DayzePvP** [comment]
Ok Thanks! But what about generating a new world/seed?

**Comment by DaMatrix** [comment]
you need to manually change the world seed, if no seed is given it generates a seed based on the hash of the world name (the seed remains constant if the world name doesn't change).
