### ISSUE TITLE
[QUESTION] Can we use Anvil formatted worlds from Nukkit 1.0 in Nukkit 2.0?

### ISSUE THREAD

**Issue by AlicanCopur** [CloudburstMC/Cloudburst#86]
Can we use Anvil formatted worlds from Nukkit 1.0 in Nukkit 2.0?

**Comment by Sleepybear** [comment]
the plan is to provide a converter that will convert Nukkit1.0 worlds to the Cloudburst Server format.

**Comment by AlicanCopur** [comment]
> 
> 
> the plan is to provide a converter that will convert Nukkit1.0 worlds to the Cloudburst Server format.

Okay, I tried use Nukkit 1.0 Anvil formatted world in Nukkit 2.0 but it converted the world to LevelDB format. Can I use the world with Anvil format? Because LevelDB formatted worlds takes a lot of space, this is a problem for skyblock server owners.
