### ISSUE TITLE
Possibility of experincing a NPE in NukkitConsole class

### ISSUE THREAD

**Issue by sero583** [CloudburstMC/Cloudburst#92]
This variable is never set, so it may bug when being used: https://github.com/CloudburstMC/Server/blob/bleeding/src/main/java/org/cloudburstmc/server/console/NukkitConsole.java#L18

**Comment by sero583** [comment]
Uhm oh, is the annotation at the start of this class forcing it to have a constructor argument?

**Comment by ghost** [comment]
@sero583 yes take a look at [this](https://projectlombok.org/api/lombok/RequiredArgsConstructor.html) this annotation generates a constructor for those final fields in this class take a look at its bytecode
