### ISSUE TITLE
Corrupted Chunks Loading Inside Imported World Chunks

### ISSUE THREAD

**Issue by DayzePvP** [CloudburstMC/Cloudburst#93]
### Expected Behavior
Imported world chunks stay the same and no other world generated chunks interfere.
Ex: A space is provided so that the imported world has space between the generated chunks so that there is no mess up with the imported world.

### Actual Behavior
Chunks are inside the imported world and mess up underground spaces (In our case) but none seem to be corrupted when getting close to the middle of the imported world chunks.

### Steps to Reproduce
1. Upload bedrock world
2. Start your server
3. Join your server then leave and restart your server
4. The glitched chunks should start appearing

![image](https://user-images.githubusercontent.com/69482212/95924848-965dda80-0d75-11eb-9b78-c45d5a501445.png)

**Comment by SupremeMortal** [comment]
I think LevelDB isn't getting enough time to compact the world before the server shuts down so the chunks never get saved.

**Comment by Sleepybear** [comment]
I have seen a few times when I go to stop the server that it hangs on stopping other threads, and then it force kills it....

**Comment by TheShermanTanker** [comment]
@Sleepybear That problem still persists now, I'm still baffled as to what causes it

**Comment by Creeperface01** [comment]
> @Sleepybear That problem still persists now, I'm still baffled as to what causes it

try item-refactor branch

**Comment by TheShermanTanker** [comment]
> 
> 
> > @Sleepybear That problem still persists now, I'm still baffled as to what causes it
> 
> try item-refactor branch

I'll try it, thanks

**Comment by Sleepybear** [comment]
I believe this has been resolved. If not, please reopen.
